# Generated by Django 5.2.4 on 2025-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha_create',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='producto_comprado',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], max_length=200),
        ),
    ]
