# Generated by Django 5.2.4 on 2025-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0003_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('Bancolombia', 'Bancolombia')], max_length=200),
        ),
    ]
